In [1]:
# import necessary libraires/packages/functions
import pandas as pd
import numpy as np

In [2]:
# read in data and create a dataframe 'df'
df = pd.read_csv('merge_data.csv')

In [3]:
# sanity checks
df.head(5)

,Unnamed: 0,Traffic Report ID,Published Date_x,Issue Reported_x,Latitude_x,Longitude_x,Address_x,Published Date_y,Issue Reported_y,Latitude_y,Longitude_y,Address_y
0,0,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15078...,10/13/2017 02:13:00 AM +0000,Traffic Impediment,30.275642,-97.767780,N Mopac Sb To Cesar Ch Eb Ramp & W Cesar Chave...,10/13/2017 02:13:00 AM +0000,Traffic Impediment,30.275642,-97.767780,N Mopac Sb To Cesar Ch Eb Ramp & W Cesar Chave...
1,1,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15082...,10/18/2017 02:23:00 AM +0000,Crash Service,30.233752,-97.740365,2241 S Ih 35 Svrd Nb,10/18/2017 02:23:00 AM +0000,Crash Service,30.233752,-97.740365,2241 S Ih 35 Svrd Nb
2,2,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15093...,10/30/2017 03:02:00 AM +0000,Traffic Hazard,30.282316,-97.727938,2100 N Ih 35 Upper Deck Sb,10/30/2017 03:02:00 AM +0000,Traffic Hazard,30.282316,-97.727938,2100 N Ih 35 Upper Deck Sb
3,3,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15095...,11/01/2017 02:52:00 AM +0000,Crash Service,30.268296,-97.740037,700 San Jacinto Blvd,11/01/2017 02:52:00 AM +0000,Crash Service,30.268296,-97.740037,700 San Jacinto Blvd
4,4,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15100...,11/07/2017 02:21:00 AM +0000,Crash Urgent,30.234103,-97.722846,S Pleasant Valley Rd & E Riverside Dr,11/07/2017 02:21:00 AM +0000,Crash Urgent,30.234103,-97.722846,S Pleasant Valley Rd & E Riverside Dr

In [4]:
df.columns

Index(['Unnamed: 0', 'Traffic Report ID', 'Published Date_x',
       'Issue Reported_x', 'Latitude_x', 'Longitude_x', 'Address_x',
       'Published Date_y', 'Issue Reported_y', 'Latitude_y', 'Longitude_y',
       'Address_y'],
      dtype='object')

#### Further Cleaning on Dataset

In [6]:
# drop uneccessary columns
df.drop(columns=['Unnamed: 0', 'Published Date_x', 'Issue Reported_x', 
                 'Latitude_x', 'Longitude_x', 'Address_x' ], inplace=True)

In [7]:
# check if columns are dropped
df.head(1)

,Traffic Report ID,Published Date_y,Issue Reported_y,Latitude_y,Longitude_y,Address_y
0,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15078...,10/13/2017 02:13:00 AM +0000,Traffic Impediment,30.275642,-97.76778,N Mopac Sb To Cesar Ch Eb Ramp & W Cesar Chave...

In [8]:
# rename the columns
df.rename(columns={'Traffic Report ID': 'Traffic_Report_ID', 'Published Date_y': 
                   'Published_Date', 'Issue Reported_y': 'Issue_Reported', 'Latitude_y': 'Latitude',
                  'Longitude_y': 'Longitude', 'Address_y': 'Address'}, inplace=True)

In [9]:
# convert column published date to datetime
df['Published_Date'] = pd.to_datetime(df['Published_Date'])

# make a column for AM and PM
df['AM_PM'] = df['Published_Date'].dt.strftime('%p')

In [10]:
# set published data as the index
df.set_index('Published_Date', inplace=True)

In [11]:
# drop rows where there is NaN latitude, longitude, and address
df.dropna(subset=['Latitude', 'Longitude', 'Address'], how='all', inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 385289 entries, 2017-10-13 02:13:00+00:00 to 2024-07-28 06:41:58+00:00
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Traffic_Report_ID  385289 non-null  object
 1   Issue_Reported     385289 non-null  object
 2   Latitude           385210 non-null  float64
 3   Longitude          385210 non-null  float64
 4   Address            385289 non-null  object
 5   AM_PM              385289 non-null  object
dtypes: float64(2), object(4)
memory usage: 20.6+ MB

In [13]:
# we still have some rows where entries of latitude and longitude are null, remove those rows.
# it is okay to do so since we need accurate longitude and latitude for visual data
df.dropna(subset=['Latitude', 'Longitude'], how='any', inplace=True)

In [14]:
# check
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 385210 entries, 2017-10-13 02:13:00+00:00 to 2024-07-28 06:41:58+00:00
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Traffic_Report_ID  385210 non-null  object
 1   Issue_Reported     385210 non-null  object
 2   Latitude           385210 non-null  float64
 3   Longitude          385210 non-null  float64
 4   Address            385210 non-null  object
 5   AM_PM              385210 non-null  object
dtypes: float64(2), object(4)
memory usage: 20.6+ MB

In [15]:
# check dataset
df.head()

,Traffic_Report_ID,Issue_Reported,Latitude,Longitude,Address,AM_PM
Published_Date,,,,,,
2017-10-13 02:13:00+00:00,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15078...,Traffic Impediment,30.275642,-97.767780,N Mopac Sb To Cesar Ch Eb Ramp & W Cesar Chave...,AM
2017-10-18 02:23:00+00:00,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15082...,Crash Service,30.233752,-97.740365,2241 S Ih 35 Svrd Nb,AM
2017-10-30 03:02:00+00:00,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15093...,Traffic Hazard,30.282316,-97.727938,2100 N Ih 35 Upper Deck Sb,AM
2017-11-01 02:52:00+00:00,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15095...,Crash Service,30.268296,-97.740037,700 San Jacinto Blvd,AM
2017-11-07 02:21:00+00:00,000B6E11CC7D4C971FBF68F3F1E28EDC93443FF3_15100...,Crash Urgent,30.234103,-97.722846,S Pleasant Valley Rd & E Riverside Dr,AM

In [16]:
# filter for only Jan 2021 to August 2024

# sort index
df.sort_index(inplace=True)
df = df.loc['2021':'2024']

In [17]:
# check if its filtered
df.head(5)

,Traffic_Report_ID,Issue_Reported,Latitude,Longitude,Address,AM_PM
Published_Date,,,,,,
2021-01-01 00:01:11+00:00,899A19B6BEC5CDDC50179F183BA138B628CF94B3_16094...,Crash Urgent,30.222103,-97.676940,1500-1578 E Sh 71 Eb,AM
2021-01-01 00:15:48+00:00,45CE120FEAA2C1A2BB53DB6C8FB833E58D6BB661_16094...,Crash Urgent,30.357592,-97.686939,801-829 E Rundberg Ln,AM
2021-01-01 00:29:25+00:00,F673929B7AE05128DD473C556386A7B585483947_16094...,Stalled Vehicle,30.218082,-97.690595,E Ben White Blvd Svrd Eb & E Riverside Dr,AM
2021-01-01 00:49:45+00:00,DF1FA50C9F190117BEC623D72ED64F655EA0360F_16094...,COLLISION,30.164672,-97.724830,7201-7241 MC KINNEY FALLS PKWY,AM
2021-01-01 00:55:29+00:00,7C9FE6831F52E30E0EDE4F8C54FD9BBA673E8D8B_16094...,Crash Service,30.373617,-97.677882,11105 N Ih 35 Svrd Nb,AM

In [18]:
# define a function that helps clean the issue reported column
def clean_issue_reported(issue):
    issue = issue.upper()

    issue = issue.replace('TRFC HAZD/ DEBRIS', 'TRAFFIC HAZARD')
    issue = issue.replace('COLLISN/ LVNG SCN', 'COLLISION')
    issue = issue.replace('COLLISION/PRIVATE PROPERTY', 'COLLISION')
    issue = issue.replace('BLOCKED DRIV/ HWY', 'BLOCKED ROADS')
    issue = issue.replace('AUTO/ PED', 'AUTO-PED')
    issue = issue.replace('COLLISION/PRIVATE PROPERTY', 'COLLISION')
    issue = issue.replace('FLEET ACC/ INJURY', 'FLEET ACCIDENT WITH INJURY')
    issue = issue.replace('N / HZRD TRFC VIOL', 'NON-HAZARDOUS TRAFFIC VIOLATION')
    
    return issue

# apply the function to column issue reported
df.loc[:, 'Issue_Reported'] = df['Issue_Reported'].apply(clean_issue_reported)

In [19]:
# check issue reported unique values
df['Issue_Reported'].unique()

array(['CRASH URGENT', 'STALLED VEHICLE', 'COLLISION', 'CRASH SERVICE',
       'TRAFFIC HAZARD', 'VEHICLE FIRE', 'LOOSE LIVESTOCK',
       'COLLISION WITH INJURY', 'BLOCKED ROADS', 'AUTO-PED',
       'TRAFFIC FATALITY', 'FLEET ACCIDENT WITH INJURY', 'ICY ROADWAY',
       'OBSTRUCT HWY', 'BOAT ACCIDENT', 'NON-HAZARDOUS TRAFFIC VIOLATION',
       'HIGH WATER'], dtype=object)

In [20]:
# remove invalid lat and long
df['Latitude'] = df['Latitude'].apply(lambda x: x if -90 <= x <= 90 else np.nan)
df['Longitude'] = df['Longitude'].apply(lambda x: x if -180 <= x <= 180 else np.nan)

# Drop rows with NaN values in the 'Latitude' column
df = df.dropna(subset=['Latitude', 'Longitude'])

In [21]:
# check
df.describe()

            Latitude      Longitude
count  184616.000000  184616.000000
mean       30.225210     -97.483934
std         1.512110       4.867751
min         0.000000     -98.767198
25%        30.229216     -97.775770
50%        30.294857     -97.727537
75%        30.374663     -97.673958
max        31.077333       0.000000

In [22]:
# check df
df

,Traffic_Report_ID,Issue_Reported,Latitude,Longitude,Address,AM_PM
Published_Date,,,,,,
2021-01-01 00:01:11+00:00,899A19B6BEC5CDDC50179F183BA138B628CF94B3_16094...,CRASH URGENT,30.222103,-97.676940,1500-1578 E Sh 71 Eb,AM
2021-01-01 00:15:48+00:00,45CE120FEAA2C1A2BB53DB6C8FB833E58D6BB661_16094...,CRASH URGENT,30.357592,-97.686939,801-829 E Rundberg Ln,AM
2021-01-01 00:29:25+00:00,F673929B7AE05128DD473C556386A7B585483947_16094...,STALLED VEHICLE,30.218082,-97.690595,E Ben White Blvd Svrd Eb & E Riverside Dr,AM
2021-01-01 00:49:45+00:00,DF1FA50C9F190117BEC623D72ED64F655EA0360F_16094...,COLLISION,30.164672,-97.724830,7201-7241 MC KINNEY FALLS PKWY,AM
2021-01-01 00:55:29+00:00,7C9FE6831F52E30E0EDE4F8C54FD9BBA673E8D8B_16094...,CRASH SERVICE,30.373617,-97.677882,11105 N Ih 35 Svrd Nb,AM
...,...,...,...,...,...,...
2024-08-16 03:48:34+00:00,DB8DC2B7A3BB754178D96FE9B4E434D0C017825B_17237...,TRAFFIC HAZARD,30.263114,-97.705584,3017 Lyons Rd,AM
2024-08-16 04:33:43+00:00,8639C2E8C44D79A5AFAF095AA46F9C9231829B72_17237...,TRAFFIC HAZARD,30.367928,-97.718562,8817-9009 Research Blvd Nb,AM
2024-08-16 04:36:35+00:00,23D202FB561C67AC5D22AE22F0E595ED35106B02_17237...,CRASH URGENT,30.205539,-97.716533,Montopolis Dr / Burleson Rd,AM
2024-08-16 05:01:51+00:00,A031EB6D2F6330F89B937098D4439578421617DF_17237...,CRASH URGENT,30.338738,-97.682241,Cameron Rd / Park Center Dr,AM
2024-08-16 06:10:40+00:00,8F48A9E0132ABD0575E1EDC471A05B67D62EED5E_17237...,CRASH URGENT,30.172380,-97.799529,S 1st St / W Slaughter Ln,AM

In [23]:
# convert df to CSV
# df.to_csv('Traffic_Records.csv', index=True)

In [24]:
df['Issue_Reported'].value_counts()

Issue_Reported
TRAFFIC HAZARD                     69715
CRASH URGENT                       46200
COLLISION                          27511
CRASH SERVICE                      21127
STALLED VEHICLE                     7233
LOOSE LIVESTOCK                     5826
COLLISION WITH INJURY               5281
VEHICLE FIRE                         901
BLOCKED ROADS                        494
AUTO-PED                             101
TRAFFIC FATALITY                      85
BOAT ACCIDENT                         52
ICY ROADWAY                           40
FLEET ACCIDENT WITH INJURY            27
OBSTRUCT HWY                          12
NON-HAZARDOUS TRAFFIC VIOLATION        8
HIGH WATER                             3
Name: count, dtype: int64

In [25]:
# combine 
df.loc[df['Issue_Reported'] == 'COLLISION WITH INJURY', 'Issue_Reported'] = 'CRASH URGENT'
df['Issue_Reported'].value_counts()

Issue_Reported
TRAFFIC HAZARD                     69715
CRASH URGENT                       51481
COLLISION                          27511
CRASH SERVICE                      21127
STALLED VEHICLE                     7233
LOOSE LIVESTOCK                     5826
VEHICLE FIRE                         901
BLOCKED ROADS                        494
AUTO-PED                             101
TRAFFIC FATALITY                      85
BOAT ACCIDENT                         52
ICY ROADWAY                           40
FLEET ACCIDENT WITH INJURY            27
OBSTRUCT HWY                          12
NON-HAZARDOUS TRAFFIC VIOLATION        8
HIGH WATER                             3
Name: count, dtype: int64

In [26]:
# combine
df.loc[df['Issue_Reported'] == 'FLEET ACCIDENT WITH INJURY', 'Issue_Reported'] = 'CRASH URGENT'
df.loc[df['Issue_Reported'] == 'OBSTRUCT HWY', 'Issue_Reported'] = 'BLOCKED ROADS'

In [27]:
df['Issue_Reported'].value_counts()

Issue_Reported
TRAFFIC HAZARD                     69715
CRASH URGENT                       51508
COLLISION                          27511
CRASH SERVICE                      21127
STALLED VEHICLE                     7233
LOOSE LIVESTOCK                     5826
VEHICLE FIRE                         901
BLOCKED ROADS                        506
AUTO-PED                             101
TRAFFIC FATALITY                      85
BOAT ACCIDENT                         52
ICY ROADWAY                           40
NON-HAZARDOUS TRAFFIC VIOLATION        8
HIGH WATER                             3
Name: count, dtype: int64

In [28]:
df_cleaned = df[df['Issue_Reported'] != 'NON-HAZARDOUS TRAFFIC VIOLATION']
df_cleaned = df_cleaned[df_cleaned['Issue_Reported'] != 'HIGH WATER']

In [29]:
df = df_cleaned
df['Issue_Reported'].value_counts()

Issue_Reported
TRAFFIC HAZARD      69715
CRASH URGENT        51508
COLLISION           27511
CRASH SERVICE       21127
STALLED VEHICLE      7233
LOOSE LIVESTOCK      5826
VEHICLE FIRE          901
BLOCKED ROADS         506
AUTO-PED              101
TRAFFIC FATALITY       85
BOAT ACCIDENT          52
ICY ROADWAY            40
Name: count, dtype: int64

In [30]:
df.to_csv('Traffic_Records.csv', index=True)